---
- name: Common tools install
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg: "{{ commontools }}"
  tags: commontools

- name: Set timezone 
  timezone:
    name: "{{ timezone }}"
  tags: commontools